### ISSUE TITLE
redundant subroutine for make_numatrix0

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#111]
When I was cleaning codes based on LGTM (directly editing the develop branch), I noticed that I have forgotten to change the old code of make_numatrix0. This was not inaccurate but assumed the use of GPU to compute nu-matrix. Because,  at the initial phase of development, I have assumed that the user changed the nu matrix when performing HMC. But now the nu-matrix is static, then one just needs to compute once before HMC-NUTS. So, it's better to use numpy using np.float64 as inputs. So, I changed the default function to the numpy versions. The old one is only useful for float32 inputs, but I decide to leave them as make_numatrix0_subtract

Because I directly committed and pushed these modifications in the develop branch, for the record I wrote this issue and closed it. 

675feeaaca2a71fc048dffa119046ef0fffb8161
22a15577495ab1c2b8f0341307b64d05b7c85075

**Comment by erwanp** [comment]
Nice that LGTM is useful !

**Comment by HajimeKawahara** [comment]
Yes! Thank you for letting me know! @erwanp
