### ISSUE TITLE
MODIT in real space evaluation

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#125]
I want to implement MODIT in real space evaluation using hjert (tagged by REDIT)

**Comment by erwanp** [comment]
Related : https://github.com/radis/radis/issues/340

DIT in real-space easily allow to use lineshape truncation. More physical for large spectra where we get to see the far-wings (typically hundreds of cm-1)

**Comment by HajimeKawahara** [comment]
we should make a mapping table between radis and exojax.

**Comment by HajimeKawahara** [comment]
#128 as first implementation.

**Comment by HajimeKawahara** [comment]
Because the new folding and F32/F64 solved the issue of residuals in MODIT, I close this issue.  
Currently, REDIT is very slow, but I decided to leave this mode (REDIT) in exojax for future improvement.
