### ISSUE TITLE
Compression of weak lines 

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#149]
CH4 has massive weak lines. I would compress them. Here is an example of CH4 in ExoMol (10to10)

![enux](https://user-images.githubusercontent.com/15956904/132267139-f91118c2-370d-414f-8a5d-41e8c1f5500f.png)

The color is # of lines per bin.

Note that there are 19 elements of the pressure broadening for the CH4 case.

**Comment by dcmvdbekerom** [comment]
You could use the same binning trick as we use for the spectral synthesis.
I haven't tested the output line list of the code below but it reduces the database from 100M to 1.5M or so lines.
This is without considering Lorentzian broadening, but if you take a=0.5 for all J-levels, you could get by with only two bins for the Lorentzian width, which would likely double the output size to ~3M or so.

The E-grid we resample to might look really course with increments of 10%, but it's not a problem because we use the weights (see also the second script for a visual support of these claims). Of course smaller steps can be used if needed.

```import numpy as np
import matplotlib.pyplot as plt

## Prepare width-axes based on number of gridpoints and linewidth data:
def init_axis(dx, arr_in):
    arr_min = np.min(arr_in)
    arr_max = np.max(arr_in) + 1e-4
    N = np.ceil((arr_max - arr_min)/dx) + 1
    arr = arr_min + dx * np.arange(N)
    return arr

## Calculate grid indices and grid alignments:   
def get_indices(arr_i, axis):
    pos    = np.interp(arr_i, axis, np.arange(axis.size))
    index  = pos.astype(int) 
    return index, index + 1, pos - index 

dv = 0.001
dxE = 0.1
E0 = 1000.0 #cm-1

v_arr = np.load('v_arr.npy')
E_arr = np.load('E_arr.npy')
A_arr = np.load('A_arr.npy')

print('Loaded {:.1f}M lines...'.format(v_arr.size*1e-6))

print('Preparing axes...')
idx = E_arr >= E0
logE_arr = np.log(E_arr[idx])
logE_ax = init_axis(dxE,logE_arr)
v_ax = init_axis(dv,v_arr)

print('Calculating weights & indices...')
M = np.zeros((v_ax.size,logE_ax.size), dtype=np.float32)
ki0, ki1, tvi = get_indices(v_arr[idx], v_ax)   
li0, li1, tEi = get_indices(logE_arr, logE_ax)

print('Populating matrix...')
np.add.at(M, (ki0, li0), A_arr[idx] * (1-tvi) * (1-tEi))
np.add.at(M, (ki0, li1), A_arr[idx] * (1-tvi) *    tEi )
np.add.at(M, (ki1, li0), A_arr[idx] *    tvi  * (1-tEi))
np.add.at(M, (ki1, li1), A_arr[idx] *    tvi  *    tEi )

print('Sorting output...')
mask = M!=0
E2_ax, v2_ax = np.meshgrid(np.exp(logE_ax), v_ax)

v_new = np.concatenate((v_arr[~idx], v2_ax[mask]))
E_new = np.concatenate((E_arr[~idx], E2_ax[mask]))
A_new = np.concatenate((A_arr[~idx], M[mask]))

print('Saving output...')
np.save('v_new.npy', v_new)
np.save('E_new.npy', E_new)
np.save('A_new.npy', A_new)

print('Reduced database to {:.1f}M lines!'.format(v_new.size*1e-6))
```

It works also for energies, you can explore visually in this code:
![image](https://user-images.githubusercontent.com/7279972/139569359-c4d7eda1-6f93-48c6-a67f-813647cc992b.png)

```
import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import h,c,k

gE = lambda T,El: np.exp(-El/T)

c_cm = 100*c
T_arr = np.arange(0,10000,1)[1:] #cm-1
k_arr = np.arange(100)

E0 = 1000
dxE = 0.1
El_arr = E0*np.exp(k_arr*dxE)

fig,ax = plt.subplots()
for El in El_arr:
    plt.plot(T_arr,gE(T_arr,El),'k-',alpha=0.25)

p_exact, = plt.plot(T_arr,gE(T_arr,E0),'r', label='exact')
p_approx, = plt.plot(T_arr,gE(T_arr,E0),'k--',label='approx.')
p_diff, = plt.plot(T_arr,np.zeros(T_arr.size),'b',label='100$\\times$ diff.')
plt.xlabel('kT/hc (cm$^{-1}$)')
plt.ylabel('exp[-hcE/kT]')
##plt.yscale('log')
##plt.ylim(0.01,1)
plt.legend(loc=2)

def approx_gE(T,El):
    Ie = gE(T,El)  
    if El > E0:
        i = np.interp(np.log(El),
                      np.log(El_arr),
                      np.arange(El_arr.size),
                      )
        i0 = int(i)
        i1 = i0+1
        t = i-i0
        a = t

        Ia = (1-a)*gE(T,El_arr[i0]) + a*gE(T,El_arr[i1])

        return Ie, Ia
    else:
        return Ie, Ie 

def on_plot_hover(event):
    if event.xdata:
        El_i = event.xdata

        Ie, Ia = approx_gE(T_arr,El_i)
        Id = 100*np.abs((Ie-Ia))

        p_exact.set_ydata(Ie)
        p_approx.set_ydata(Ia)
        p_diff.set_ydata(Id) 
        fig.canvas.draw_idle()

fig.canvas.mpl_connect('motion_notify_event', on_plot_hover)    

plt.show()
```

**Comment by erwanp** [comment]
Note 1 : @dcmvdbekerom your example does not use degeneracies, they should be accounted for in real-case examples. 

Note2 : using Vaex, the binning can be done on disk. This will save - a lot - of RAM memory. It should be very similar to how it's implemented for TIPS in RADIS  (it's the same equation). [See a vaex-tabulatino here](https://github.com/radis/radis/blob/7cb634cd5741a8c50b8c0f8e3d3d2ce5b8c6afc7/radis/levels/partfunc.py#L284).

Note 3 : won't work for non-LTE (lines do not follow the same dependance, you'd need a higher dimensional tabulation)

**Comment by HajimeKawahara** [comment]
@dcmvdbekerom @erwanp Thank you for the suggestions. I've been leaving this issue alone for a couple of months, but I'm going to rethink it because the resubmission has been done. At that time (2 months ago) I think I have a similar implementation in mind: i.e. binning in E_lower (and wave number) grid. [This ](https://github.com/HajimeKawahara/exojax/blob/features/compression/src/exojax/spec/plg.py) was some attempts at that time. If we can do the binning in vaex, it's very nice otherwise we need to precompute something using a machine having a huge DRAM.

**Comment by erwanp** [comment]
Definitly doable in Vaex, that's what's done in the RADIS example above for partition sums !

(remember that Vaex is not faster;  but out-of-core. For heavy computations you always want to use your RAM as much as possible... without saturating it !)
