### ISSUE TITLE
Multispecies MODIT

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#207]
@chonma0ctopus 
VALD3 has multiple species. So, probably,  in order to reduce the number of calls of modit, we need to sum up all the species before FFT.

**Comment by erwanp** [comment]
Hello @HajimeKawahara

This might not be a good idea. DIT complexity increases with the number of points in the DIT grid. If all your species have very different lorentzian widths, you may end up with a large but sparse DIT grid resulting in long computational times.

In Radis 0.12 I introduced a sparse version of the DIT algorithm (paper not even started, maybe in the summer) which fixes this. I could try to implement it in Exojax at some point. In the meantime, just be aware that multiple calls to grouped moddit may be much more efficient than a call to a large sparse moddit base

**Comment by HajimeKawahara** [comment]
Hi! @erwanp We have 1 to tens different metal species in VALD3. So, I thought, instead of adding the Doppler direction to MODIT (i.e. this is just DIT),  we could just add a summation for species in MODIT algorithm. But, yes I agree, different species mean the different (wide) range of Lorentzian too. This might lead to a sparse grid, as you said. Currently, @chonma0ctopus is trying to apply multiple calls of MODIT in the meantime. But, the sparse version of (MO)DIT will improve the performance of ExoJAX for many practical problems!
