### ISSUE TITLE
multiple HITEMP2010 file

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#213]
H2O and CO2 of HITEMP2010 contain multiple files. We need to add the capability to load multiple files for the HITRAN form too.
https://hitran.org/hitemp/

**Comment by erwanp** [comment]
Already done in Radis btw, we can just borrow from there.

Radis.io.hitemp.fetch_hitemp yields a Vaex or Pandas dataframe

**Comment by HajimeKawahara** [comment]
looks nice! I think, @ykawashima is now trying to get the code working for the next release ([v1.1](https://github.com/HajimeKawahara/exojax/milestone/4)) , but after that, I think it's time we had a discussion about a common I/O module. Do you have any idea on that?

**Comment by ykawashima** [comment]
That looks great! I have just sent a pull request that allows loading multiple par files of HITEMP H2O and CO2 in the meanwhile.

**Comment by HajimeKawahara** [comment]
resolved in #216
