### ISSUE TITLE
How to connect DataFrame in a common API to ExoJAX

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#256]
- Need to understand how it works by reviewing [this PR in radis](https://github.com/radis/radis/pull/465)
- Think conversion of moldb.py to DataFrame 
@ykawashima @chonma0ctopus

**Comment by HajimeKawahara** [comment]
Using [a retrieval w/ CH4](https://github.com/HajimeKawahara/exojax/blob/develop/tests/manualtest/reverse/reverse_methane.py) as an example, I am checking which part should be replaced by a common API.

## ExoMol
### init_modit
[here](https://github.com/HajimeKawahara/exojax/blob/6997e0b5d9e11406a695c426299fda74b17b8396/tests/manualtest/reverse/reverse_methane.py#L72)
```python
cnu, indexnu, R, pmarray = initspec.init_modit(mdbCH4.nu_lines, nus)
```
- [ ] nu_lines, looks easy to be replaced, already implemented? 

### in setdgm_exomol, exomol
[here](https://github.com/HajimeKawahara/exojax/blob/6997e0b5d9e11406a695c426299fda74b17b8396/tests/manualtest/reverse/reverse_methane.py#L83) and [here](https://github.com/HajimeKawahara/exojax/blob/6997e0b5d9e11406a695c426299fda74b17b8396/tests/manualtest/reverse/reverse_methane.py#L100)
```python
dgm_ngammaL = setdgm_exomol(mdbCH4, fT, Parr, R, molmassCH4, res, T0_test, alpha_test)
```
or
```python
SijM_CH4, ngammaLM_CH4, nsigmaDl_CH4 = modit.exomol(
        mdbCH4, Tarr, Parr, R, molmassCH4)
```

[The destination is modit.exomol](https://github.com/HajimeKawahara/exojax/blob/6997e0b5d9e11406a695c426299fda74b17b8396/src/exojax/spec/modit.py#L256)
```
    qt = vmap(mdb.qr_interp)(Tarr)
    SijM = jit(vmap(SijT, (0, None, None, None, 0)))(
        Tarr, mdb.logsij0, mdb.dev_nu_lines, mdb.elower, qt)
    gammaLMP = jit(vmap(gamma_exomol, (0, 0, None, None)))(
        Parr, Tarr, mdb.n_Texp, mdb.alpha_ref)
    gammaLMN = gamma_natural(mdb.A)
    gammaLM = gammaLMP+gammaLMN[None, :]
    ngammaLM = gammaLM/(mdb.dev_nu_lines/R)
```
- [ ] (relative) partition function, `qr_interp`, need to be considered
- [ ] logsij0, looks relatively easy to be replaced
- [ ] nu_lines in jnp.array, already almost implemented 
- [ ] elower,  already implemented 
- [ ] pressure broadening parameters, `n_Texp, alpha_ref`, already implemented?
- [ ] Einstein coefficient, already implemented 

### CIA
[here](https://github.com/HajimeKawahara/exojax/blob/6997e0b5d9e11406a695c426299fda74b17b8396/tests/manualtest/reverse/reverse_methane.py#L107)
```python
    dtaucH2H2 = dtauCIA(nus, Tarr, Parr, dParr, vmrH2, vmrH2,
                        mmw, g, cdbH2H2.nucia, cdbH2H2.tcia, cdbH2H2.logac)
```
I think we should postpone CIA meanwhile. But it should be included in the common API in the future?

**Comment by HajimeKawahara** [comment]
@erwanp 

Hello! Sorry for long silence. I have been busy the past few months as I moved from University of Tokyo to [JAXA/ISAS](https://www.isas.jaxa.jp/en/) (change my institution in your slide). Anyway, I manage to start a common API issue.  

Currently, I am trying to use `fetch_exomol` as an interface 
 ([here](https://github.com/HajimeKawahara/exojax/blob/b7ce4f2f5ff90367884b8a73e9fe9443ad95a193/src/exojax/spec/moldf.py#L92))

```python
        dataframe = fetch_exomol(self.simple_molecule_name,
                                 database=self.database,
                                 local_databases=self.path)
```
But I am wondering how we should call pf (partition function) info. Sofar we used `exomolapi.read_pf` in exojax.
([here](https://github.com/HajimeKawahara/exojax/blob/b7ce4f2f5ff90367884b8a73e9fe9443ad95a193/src/exojax/spec/moldf.py#L120))
```python
        # load pf
        pf = exomolapi.read_pf(self.pf_file)
        self.gQT = jnp.array(pf['QT'].to_numpy())  # grid QT
        self.T_gQT = jnp.array(pf['T'].to_numpy())  # T forgrid QT
        self.QTref = np.array(self.QT_interp(Tref))
        self.QTtyp = np.array(self.QT_interp(self.Ttyp))
```

I'd like to hear your opinion.

**Comment by erwanp** [comment]
Hello, congrats on the move ! Our lab worked with Kazuhisa Fujita-sama at JAXA, if you happen to meet him. 

--


Side note, I think you shouldn't use [fetch_exomol()](https://github.com/radis/radis/blob/add/common-api/radis/io/exomol.py#L20) directly. It includes some RADIS specific features, such as storing databases in `~/.radisdb` or registering them in `radis.json` (which is useful, but should not be required by Exojax). Also, it renames columns in a RADIS-specific format.
Instead, I suggest you use the underlying class from the common API, [MdbExomol](https://github.com/radis/radis/blob/add/common-api/radis/io/exomol.py#L202)

--
 
For Partition Functions, I used a RADIS-specific [mdb.to_partition_function_tabulator()](https://github.com/radis/radis/blob/add/common-api/radis/io/exomol.py#L315) function, which generates [PartFuncExoMol](https://github.com/radis/radis/blob/31b5e197f4894a82d143ae331211f9bba1152d05/radis/levels/partfunc.py#L1117), basically just an interpolator which returns  `np.interp(T, self.T_range, self.Q_range)`

I think you should keep on using the ExoJax syntax you showed above. `T_gQT`, `qGT` can be retrieved from the MdbExoMol object : 

```python
  mdb = MdbExomol(
      local_path,
      molecule=molecule,
      name=databank_name,
      local_databases=local_databases,
      nurange=[
          load_wavenum_min if load_wavenum_min is not None else 0.0,
          load_wavenum_max if load_wavenum_max is not None else np.inf,
      ],
      engine=engine,
      cache=cache,
      skip_optional_data=skip_optional_data,
  )
#...
T_gQT, gQT = mdb.T_gQT, mdb.gQT

``` 

(link to [common-api](https://github.com/radis/radis/tree/add/common-api) branch)

**Comment by HajimeKawahara** [comment]
Hello @erwanp,

Thanks a lot. I see. Then, first, I will try to wrap `radis.api.exomol.MdbExomol` in `exojax.spec.api.MdbExomol`. 
I think, in near future, maybe we should directly call `radis.api.exomol.MdbExomol` but now, I feel the wrapping is more safe.

**Comment by erwanp** [comment]
Yes, agreed. These API will take some time before they reach their final form. Even after you call `radis.api.exomol.MdbExomol` I'd suggest to Inherit() and Subclass the Radis class so you can easily override anything at anytime if needed (without having to require any RADIS update).

So  in `exojax/spec/api`

```python
from radis.api.exomol import MdbExomol 

class MdbExoMol(MdbExomol):
    ... 
```

**Comment by HajimeKawahara** [comment]
@erwanp 

I think I managed to connect [radis/api/exomolapi.py](https://github.com/radis/radis/blob/add/common-api/radis/api/exomolapi.py) (working at common-api branch) to [exojax/spec/api.py](https://github.com/HajimeKawahara/exojax/blob/radisapi/src/exojax/spec/api.py) (working at radisapi branch) for ExoMol. 

### tests in ExoJAX
- exojax/tests/integration/moldb

### tests in radis
- radis/radis/test/io

Before I move on HITEMP, I'd like you to make sure this is the right direction. I found, for HITEMP unlike ExoMol, MdbExomol like class does not exist in radis yet. Instead, I found `HITEMPDatabaseManager`. What are your thoughts on how to connect radis HITEMP API to ExoJAX?

**Comment by erwanp** [comment]
Hello ! `HITEMPDatabaseManager` inherits from `DatabaseManager`, similarly to `MdBExomol`. Therefore, HITEMPDatabaseManager will play the same role  as `MdBExomol` in the API. 

So it should be fairly easy to just duplicate the changes, unless you see a problem I missed ?

**Comment by HajimeKawahara** [comment]
OK, then, I will try to implement it the same way as mdbExomol 😃 Thanks!

**Comment by HajimeKawahara** [comment]
@erwanp 
Hello! I have a question on `hapi` in `radis`. It looks that the installation of `radis` automatically installs `hapi`. Is it correct? If true, how does it work?

**Comment by HajimeKawahara** [comment]
@erwanp Sorry to keep asking questions. What is the main reason for implementing hitranapi and hitempapi separately? Maybe data format?

**Comment by erwanp** [comment]
Many parts are common,  but the download is different.
And Hitran has more columns than the default ones, we currently have a project https://github.com/radis/radis/pull/495  to automatically include the broadening coefficients of non-air species. This is a Hitran only feature.

**Comment by erwanp** [comment]
> @erwanp Hello! I have a question on `hapi` in `radis`. It looks that the installation of `radis` automatically installs `hapi`. Is it correct? If true, how does it work?

Hapi is pip installable. The pip package name is `hitran-api`
https://github.com/radis/radis/blob/develop/environment.yml

**Comment by HajimeKawahara** [comment]
>Hapi is pip installable. The pip package name is hitran-api

Thanks! Oh really. I did not notice that.

> Many parts are common, but the download is different.
And Hitran has more columns than the default ones, we currently have a project https://github.com/radis/radis/pull/495 to automatically include the broadening coefficients of non-air species. This is a Hitran only feature.

I see. So, it's presumably better to have separate moldbs in ExoJAX too.

**Comment by HajimeKawahara** [comment]
#309 removed the old moldb. So, now ExoJAX officially determined to use radis.api as I/O of ExoMol, HITRAN, and HITEMP.
