### ISSUE TITLE
Divergences appear when reverse modeling with Premodit or PLG with FP32

### ISSUE THREAD

**Issue by chonma0ctopus** [HajimeKawahara/exojax#268]
When you run reverse modeling with Premodit (e.g., [reverse_premodit.py](https://github.com/HajimeKawahara/exojax/blob/ad318dd34e6f49b19473a26335efdd7b52ee41ca/tests/endtoend/reverse/reverse_premodit.py)) with FP32 (JAX default), the Number of divergences rises to more than one-third (in sometimes, one-first!) of the total number of sampling. PLG also causes non-zero divergences.

for example, the output of mcmc.print_sammary() is the below.
The num_warmup and num_samples are 1000 and 2000, respectively.
```
                mean       std    median      5.0%     95.0%     n_eff     r_hat
   MMR_CH4      0.01      0.00      0.01      0.00      0.01    298.73      1.00
        RV     10.89      1.46     10.95      8.57     13.25    546.95      1.00
        Rp      0.70      0.23      0.65      0.40      1.07    331.73      1.00
        T0   1227.93     98.34   1225.70   1062.27   1390.49    206.51      1.00
     alpha      0.08      0.01      0.08      0.06      0.10    284.75      1.00
     vsini     20.60      2.40     20.60     16.98     24.57    781.82      1.00

Number of divergences: 680
```

This can be avoided by using FP64. (It reduces user-friendliness though...)
```
from jax.config import config
config.update("jax_enable_x64", True)
```
The output of mcmc.print_sammary() after using FP64 (without any other changes) is below:
```
                mean       std    median      5.0%     95.0%     n_eff     r_hat
   MMR_CH4      0.01      0.00      0.00      0.00      0.01    438.90      1.00
        RV     10.93      1.50     10.91      8.31     13.32    758.56      1.01
        Rp      0.70      0.23      0.65      0.40      1.06    571.41      1.01
        T0   1234.90     90.99   1228.09   1088.63   1396.25    335.47      1.01
     alpha      0.08      0.01      0.08      0.07      0.10    414.25      1.01
     vsini     20.70      2.32     20.71     17.37     24.69   1013.15      1.00

Number of divergences: 0
```

This could be due to a shortage of dynamic range during FFT.

**Comment by HajimeKawahara** [comment]
Thanks for the report! 
We should decide if FP64 is the default setting... (then, people who wanna do retrievals needs a TESRA class GPU though)
