### ISSUE TITLE
gas experiment using HITRAN 2020

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#289]
This is not an issue strictly speaking, but, @KoHosokawa needs to simulate absorption lines using HITRAN2020 under H/He background atmosphere. Currently, we need to use `radisapi` branch and [add/common-api](https://github.com/radis/radis/tree/add/common-api) branch in `radis`.  See #256.

**Comment by erwanp** [comment]
Hello! I can add merge the required branch in Radis this weekend!

**Comment by HajimeKawahara** [comment]
Hi! Thanks. It makes things simple.

**Comment by KoHosokawa** [comment]
Hi!  Nice to seeing you @erwanp, thank you for your help. I'll soon study and try to use radisapi later.

**Comment by erwanp** [comment]
Hello. Common-api was merged in Radis's develop branch https://github.com/radis/radis/pull/480 

It will be released in the upcoming Radis version 0.14 later this week. 

We'll also merge https://github.com/radis/radis/pull/495 , which implements in Radis (and therefore the API) the non-air broadening parameters , which you'll probably need  @KoHosokawa for your experiment. You'll be one of the first users!  

Also check the new HITRAN paper https://iopscience.iop.org/article/10.3847/1538-4365/ac83a6

**Comment by HajimeKawahara** [comment]
> We'll also merge https://github.com/radis/radis/pull/495 , which implements in Radis (and therefore in the API) the non-air broadening parameters

Cool! Thanks a lot! @erwanp

**Comment by KoHosokawa** [comment]
> We'll also merge https://github.com/radis/radis/pull/495 , which implements in Radis (and therefore in the API) the non-air broadening parameters , which you'll probably need @KoHosokawa for your experiment. You'll be one of the first users!
Thank you for the fantastic job! I'm honored to be the first to use it.
