### ISSUE TITLE
np.unique RAM issue 

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#314]
@ykawashima pointed out that numerous RAM is used in `init_premodit` in the case of our favorite CH4 ExoMol database. This looks actually from [here](https://github.com/HajimeKawahara/exojax/blob/33a82c308c50740f8b50a1be6436d8ffd0fce3c9/src/exojax/utils/indexing.py#L21).

```
uniqvals = np.unique(input_array, axis=0)
```

I found there is some info about `np.unique(a,axis=0)` on [here](https://github.com/numpy/numpy/issues/15713). I will see.

**Comment by HajimeKawahara** [comment]
According to [this post](https://discuss.dizzycoding.com/find-unique-rows-in-numpy-array/?amp=1), Answer #4, 

```python
def unique_rows(data):
    uniq = np.unique(data.view(data.dtype.descr * data.shape[1]))
    return uniq.view(data.dtype).reshape(-1, data.shape[1])
```
looks save RAM.

**Comment by HajimeKawahara** [comment]
But, this makes such error... for large memory
```python
E       ValueError: When changing to a larger dtype, its size must be a divisor of the total size in bytes of the last axis of the array.
```

**Comment by erwanp** [comment]
Can you do premodit fully in Vaex? This would fix your RAM problem

**Comment by HajimeKawahara** [comment]
Ah, good idea! I will consider this possibility.

**Comment by HajimeKawahara** [comment]
Meanwhile, #315 implemented the above code.  @ykawashima confirmed that it improved the RAM use when CH4/ExoMol is used.
