### ISSUE TITLE
Vaexization of some algorithm

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#316]
[Commented](https://github.com/HajimeKawahara/exojax/issues/314#issuecomment-1309887464) by @erwanp. Consider replacing some parts in PreMODIT to use Vaex directly. I need to get a little more familiar with Vaex though.

**Comment by erwanp** [comment]
On my side I'd have to get a bit more familiar with premodit. Can we set up a quick call?

I understand they premodit does some kind of binning of lines. 
If that's the case, you can definitely do it in Vaex, I..e, before loading into RAM. Its slower than in RAM, but no memory usage.

Let's discuss more on Slack?

**Comment by HajimeKawahara** [comment]
Thanks! Yeah, let's go to Slack
