### ISSUE TITLE
Test file for Exomol/Hitemp (api)

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#340]
We have used pickled class object of api.py, i.e. `mdbExomol,` `mdbHitemp`. But, this contains vaex object, such as `vaex.hdf`. It yields problems because it depends on environment. So, we need hdf based test file, for CO/Exomol and CO/Hitemp.

**Comment by HajimeKawahara** [comment]
working branch: testdata
- [ ] test files for Exomol
- [ ] check for Exomol
- [ ] test par files for HITEMP
- [ ] convert to HDF5 or directly load it?
- [ ] check for hitemp

**Comment by HajimeKawahara** [comment]
Also, the direct load from user-defined par file might be useful for old users of HITRAN/HITEMP (I mean older version of par file etc.).

**Comment by erwanp** [comment]
Btw we have some test files packaged with RADIS (very light files, just used for unit-tests) available with [radis.test.utils.getTestFile](https://radis.readthedocs.io/en/latest/source/radis.test.utils.html#radis.test.utils.getTestFile); here is the list  https://github.com/radis/radis/tree/develop/radis/test/files

**Comment by HajimeKawahara** [comment]
Thanks! That looks useful. We have the same issue for unit-tests.
