### ISSUE TITLE
Operators on Spectra classes

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#363]
With the enhancement of functionality for spectra (e.g. rotational broadening, velocity shift, instrumental response, and several convolution algorithms etc..), the structure has become more complex, so we would like to create a single class in the form of separable operators for spectra.

- [x] initialization with `vr_array`
- [x] selection of the convolution method, related: #348 #362 (i.e. [exojax.signal.convolve](https://github.com/HajimeKawahara/exojax/blob/master/src/exojax/signal/convolve.py) (manual FFT-based convolution),  kernex, etc )
- any other idea?
- operators for a single spectrum (sos)
- operators for a multiple spectrum set (most), i.e. future extension of wind analysis #96 

![image](https://user-images.githubusercontent.com/15956904/226147023-28252f19-a0f0-41b3-b1ce-8e4133050533.png)

**Comment by erwanp** [comment]
For inspiration have a look at Spectrum in Radis and Spectrum1D in Astropy
