### ISSUE TITLE
Remove duplicates within classes MdbHitemp and MdbHitemp in apy.py

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#368]
We have many duplicate instances in classes `MdbHitemp` and `MdbHitemp` in apy.py.

Idea: 
- make a common class, such as `MdbCommonHitran`  and include duplicate instances in it
- `MdbHitran` inherits both `mdbHitran` from radis and `MdbCommonHitran`  
- `MdbHitemp` inherits both `mdbHitemp` from radis and `MdbCommonHitran`

**Comment by HajimeKawahara** [comment]
consider to use `__slots__` as data instances.

**Comment by HajimeKawahara** [comment]
+ H2, CO2 broadenings

**Comment by erwanp** [comment]
Hello this can be given to the intern working on the Common API if we get the GSOC funding. 📚 GSOC project : Common API radis/radis#558

Unless it's high priority (coding will start June, first results July)

**Comment by HajimeKawahara** [comment]
I see. I will check if I can fix it easily or not after merging #372

**Comment by HajimeKawahara** [comment]
#374

**Comment by HajimeKawahara** [comment]
Question: is the non-air broadening (i.e. `extra_params` in `HITRANDatabaseManager` of `radis`) applicable to HITEMP too?

@erwanp @ykawashima @KoHosokawa 
📚 GSOC project
https://github.com/radis/radis/issues/558

**Comment by HajimeKawahara** [comment]
#377
