### ISSUE TITLE
Can't download HDO from exomol.

### ISSUE THREAD

**Issue by HibikiYama** [HajimeKawahara/exojax#528]
I found that `MdbExomol` of Exojax ver1.5 can't download HDO from exomol.
When I run 
`mdb1H2HO = MdbExomol('../../../data_mol/.database/H2O/1H-2H-16O/VTT', nurange=nu_grid, gpu_transfer=False)
print('N=', len(mdb1H2HO.nu_lines))
diffmode = 0
opa = OpaPremodit(mdb=mdb1H2HO,
                  nu_grid=nu_grid,
                  diffmode=diffmode,
                  auto_trange=[Tlow, Thigh],
                  dit_grid_resolution=1.0)`,
then I got 
`/home/yama/intbase/intenv/lib/python3.9/site-packages/exojax/utils/molname.py:178: FutureWarning: e2s will be replaced to exact_molname_exomol_to_simple_molname.
  warnings.warn(
HITRAN exact name= HD(16O)
HITRAN exact name= HD(16O)
Background atmosphere:  H2
Downloading http://www.exomol.com/db/HHO/1H-2H-16O/VTT/1H-2H-16O__VTT.def and saving as ../../../data_mol/.database/H2O/1H-2H-16O/VTT/1H-2H-16O__VTT.def`
and
`URLError: <urlopen error [Errno -3] Temporary failure in name resolution>`.

It is not an appropriate URL.
Appropriate URL:
[https://exomol.com/data/molecules/H2O/1H-2H-16O/VTT/](https://exomol.com/data/molecules/H2O/1H-2H-16O/VTT/)

**Comment by HajimeKawahara** [comment]
Thanks for reporting the bug!

The correct URL: https://www.exomol.com/db/H2O/1H-2H-16O/VTT/1H-2H-16O__VTT.def
The current URL name:  https://www.exomol.com/db/HHO/1H-2H-16O/VTT/1H-2H-16O__VTT.def

So this looks like because of the name parser. I will modify it.

**Comment by HajimeKawahara** [comment]
@HibikiYama 

I had to fix the code on the Radis side, so I made the necessary corrections and submitted a pull request (PR). With this revised version, it should now be possible to download the data.

https://github.com/radis/radis/pull/693
