### ISSUE TITLE
Unit test contributions?

### ISSUE THREAD

**Issue by gully** [HajimeKawahara/exojax#86]
Hello :wave: 
Thank you for sharing your nice code :stars:  :earth_asia:! 

I am experimenting with exoJAX and see an opportunity to add some unit tests.  Would you welcome contributions of unit tests?  If so, are you open to adopting the `py.test` framework?  This would be an optional installation, and I think nothing would change to the codebase other than the addition of a `tests/` directory in the root of the project with some test scripts.

The main things I want to test automatically are:
- [ ] That the installation proceeded correctly (useful when building both exojax and numpyro from source on different machines)
- [ ] That the GPU-dependent codes are working with the right CUDA version
- [ ] That basic methods work as expected.

**Comment by HajimeKawahara** [comment]
Hello! Yes, sure. Thank you for proposing this. Honestly, I am not familiar with pytest. Let me know if there is anything I need to do.
